{% set version_match = load_file_regex(load_file="Stoner/__init__.py", regex_pattern='__version__\s*=\s*"([^"]+)"') %}
{% set version = version_match[1] %}
{% set name = "Stoner" %}

package:
  name: '{{ name|lower }}'
  version: {{ version }}

source:
  path: ..

build:
  noarch: python
  number: 1
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python >=3.11
    - pip
    - setuptools >=61.0
    - wheel

  run:
    - python >=3.11
    - asteval
    - chardet >=5.2.0
    - h5py
    - lmfit >=1.3
    - looseversion >=1.0
    - matplotlib >=3.8
    - multiprocess >=0.70
    - numpy >=2.0
    - packaging
    - pandas
    - pillow
    - python-dateutil >=2.8
    - scikit-image >=0.24
    - scipy >=1.14
    - statsmodels

about:
  home: https://github.com/stonerlab/Stoner-PythonCode/
  license: GPL-3.0-only
  license_family: GPL
  license_file: LICENSE.md
  summary: Library to help write data analysis tools for experimental condensed matter physics.
  description: The Stoner Python package is a set of utility classes for writing data analysis code. It was written within the Condensed Matter Physics group at the University of Leeds as a shared resource for quickly writing simple programs to do things like fitting functions to data, extract curve parameters, churn through large numbers of small text data files and work with certain types of scientific image files.
