engines:
    duplication:
        enabled: true
        exclude_paths:
         - doc/**
    bandit:
        enabled: true
    propspector:
        enabled: true
    pylint:
        enabled: true



exclude_paths:
    - 'build/**'
    - 'dist/**'
    - 'recipe/**'
    - 'sample-data/**'
    - 'Stoner.egginfo/**'
    - 'tests/**'
    - 'setup.py'
    - '**/conf.py'
    - 'doc/modified_plot_directive.py'

