
name: Conda

on:
  workflow_dispatch:
  release:
    types: ['released', 'prereleased']

# workflow_dispatch:        # Un comment line if you also want to trigger action manually

jobs:
  conda_deployment_with_new_tag:
    name: Conda deployment of package for platform ${{ matrix.os }} with Python ${{ matrix.python-version }}
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - name: Conda environment creation and activation
        uses: mamba-org/setup-micromamba@add3a49764cedee8ee24e82dfde87f5bc2914462 # v2.0.7
        with:
          environment-file: recipe/build-env.yml
          environment-name: build-environment
          create-args: python=3.12
          init-shell: bash
      - name: Build and upload the conda packages
        uses: uibcdf/action-build-and-upload-conda-packages@aac1ccb14aa0d4d43a0b10c18b17c5285a746544 # v1.5.0
        with:
          meta_yaml_dir: recipe
          overwrite: true
          python-version: "3.12"
          user: phygbu
          label: main
          token: ${{ secrets.ANACONDA }} # Replace with the right name of your secret

  pypi_deployment:
    name: PyPI deployment of package
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - name: Set up Python
        uses: actions/setup-python@a309ff8b426b58ec0e2a45f0f869d46889d02405 # v6.2.0
        with:
          python-version: "3.12"
      - name: Install build tools
        run: pip install build==1.2.2
      - name: Build package
        run: python -m build
      - name: Upload to PyPI
        uses: pypa/gh-action-pypi-publish@ed0c53931b1dc9bd32cbe73a98c7f6766f8a527e # v1.13.0
        with:
          password: ${{ secrets.PYPI }}
